### ISSUE TITLE
Support of Mermaid charts for Markdown files

### ISSUE THREAD

**Issue by pylapp** [swiftlang/swift-docc#1026]
### Feature Name

Support of Mermaid charts in HTML pages

### Description

Today, *markdown* files can contain charts so as to explain things or display workflows for example.
Instead of using images, charts can be designed simply with text content thanks to tools like [Mermaid](https://mermaid.js.org/).

In addition, this tool is supported in GitHub side and helps people to draw charts simply: the content is written in text, placed in the markdown, and then rendered using [Mermaid.js](https://github.com/mermaid-js/mermaid).

You can find the announcement of GitHub [in this page](https://github.blog/developer-skills/github/include-diagrams-markdown-files-mermaid/).

### Motivation

Having charts nicely rendered in the generated DocC file will help users to read them and unserstand aprts of the project for example.

For example, given the [following README file](https://github.com/Orange-OpenSource/ouds-ios/blob/develop/OUDS/README.md), the rendering of the HTML generated page using version 1.4.2 of _swift-docc_ is this one.
![Capture d’écran 2024-09-12 à 15 53 34](https://github.com/user-attachments/assets/47021708-85e5-40b6-a582-1887fa94a2c4)

If the file is viewed through GitHub web site, the rendering is done with automatically zooms and other features.
![Capture d’écran 2024-09-12 à 15 54 10](https://github.com/user-attachments/assets/6f598216-7903-4210-be8d-4e3865e6b0b8)

### Importance

This is a new feature which will help users and prevent them to go to the project repository through GitHub to get the documentation. The need can be filled with images of the charts must maanging images is not interesting.

### Alternatives Considered

None, maybe images of charts but we don't want that.

**Comment by heckj** [comment]
@pylapp I think this likely resides with `swift-docc-render`, where there's an existing issue requesting this support: https://github.com/swiftlang/swift-docc-render/issues/413. This repo is the face of docc, but the actual rendering of content happens in the other repo, and the source of this repo is more focused on data transformation for symbol graphs into docc archives that are in turn rendered by https://github.com/swiftlang/swift-docc-render/

**Comment by pylapp** [comment]
Ok so I will close that issue because it seems it is not relevant for this project and another oldone already exists. Thanks for the explainations!
