### ISSUE TITLE
Peak memory metric on Linux could be slightly more performant

### ISSUE THREAD

**Issue by icanzilb** [swiftlang/swift-docc#1066]
### Feature Name

Slightly more optimal peak memory metric on Linux

### Description

When I pulled DocC into our project our linter pointed me a small optimization in `PeakMemory.swift`, namely to fold a `filter` and `first` into `first(where:)` (Who knew swiftlint did that too?)

### Motivation

It makes a micro-difference when running on an automation in a Linux image

### Importance

A very low priority

### Alternatives Considered

The only alternative I see is to leave the code as-is

**Comment by d-ronnqvist** [comment]
I think "micro difference" is overstating the impact of this. The combined `filter` and `first` lines only take up 0.1 % of the time to compute this value. 
<img width="688" alt="Screenshot 2024-10-21 at 12 06 06" src="https://github.com/user-attachments/assets/b0031193-3018-456a-8fb0-0deddb4600dd">

Like I said in https://github.com/swiftlang/swift-docc/pull/1067#pullrequestreview-2381605723;
> If we wanted to address the performance of this code we should avoid splitting all the lines (which is where ~80% of the time is spent) and find the "VmPeak" line in a way that avoids new allocations.
