### ISSUE TITLE
Diagnose invalid characters in bundle identifiers

### ISSUE THREAD

**Issue by franklinsch** [swiftlang/swift-docc#290]
DocC should emit a diagnostic for bundle identifiers that contain characters that aren't valid in URL host (e.g., spaces).

### Steps to Reproduce

Create a DocC catalog with a space in its bundle identifier. DocC doesn't produce a diagnostic, even though spaces aren't allowed in bundle identifiers because they're URL hosts.

### Swift-DocC Version Information

**Swift-DocC version:** All

**Comment by sevki** [comment]
this is also true for other unicode code points, for instance I have a function decl which looks like
```swift
public func 𝄞(@PitchBuilder _ makeAbsolutePitches: () -> [Pitch]) -> Track {
    Track(makeAbsolutePitches())
}
```
it doesn't work if you use 
```markdown
``𝄞(_:)``
```
docc will complain
> /Users/sevki/src/Beato/Sources/Beato/Documentation.docc/Documentation.md:7:45: warning: Link destination '𝄞(_:)' is not a valid URL

which is a bit hand wavy, cause it can resolve that name to [`https://beato.sevki.dev/documentation/beato/_(_:)`](https://beato.sevki.dev/documentation/beato/_(_:)) when it's enumerating functions. 

## TD;DR
![Screenshot 2022-06-16 at 14 49 05](https://user-images.githubusercontent.com/429977/174085480-eb490f0f-e5b3-474d-9cf3-2efa75f9a31b.png)

**Comment by franklinsch** [comment]
Thanks for pointing this out @sevki! I believe this is an unrelated issue. @d-ronnqvist I believe you investigated something like this in the past?

**Comment by d-ronnqvist** [comment]
Yes, the (unrelated) issue with unicode code points in symbol links is resolved on the 5.9 branch (which is included in the Xcode 15 betas).

**Comment by agisilaos** [comment]
@franklinsch @d-ronnqvist I would love to work on this. Can you please give me some first pointers on where to look so I can try and fix the bug?

**Comment by agisilaos** [comment]
@franklinsch @d-ronnqvist Actually I decided to give it a go! Please let me know what you think: https://github.com/swiftlang/swift-docc/pull/1012

**Comment by d-ronnqvist** [comment]
@agisilaos I'm happy to hear that you want to work on this. I didn't have time to provide any first pointers beforehand, but I tried to give some suggestions about where to start in https://github.com/swiftlang/swift-docc/pull/1012#pullrequestreview-2250516723. Don't hesitate to reach out if you have any questions.

**Comment by agisilaos** [comment]
@d-ronnqvist Thank you so much. I will take a look and fix all the issues you mentioned. Appreciate the thorough review.
