### ISSUE TITLE
Any way to merge the index.json for multiple framework hosting on single Static site ?

### ISSUE THREAD

**Issue by dreampiggy** [swiftlang/swift-docc#745]
May related to https://github.com/apple/swift-docc/issues/328

### Issue

Currently seems the `index.json` is used for left search filed searching the symbols.

However, the [`swift-docc-render/src/utils/data.js`](https://github.com/apple/swift-docc-render/blob/ef24e3beb21d2f50e988778645886cbb47eadb80/src/utils/data.js#L135) here seems only support query single one `index.json` in the whole site.

So, for Static site hosting, does this means I need to merge all the other frameworks into the final big index json files ? Is there any tools to do this ?

### Alternate way

Currently in my example, I change this into `index/${framework_name}/index.json` and hosting multiple frameworks documentation.

```
- documentation/
  foo/index.html
  bar/index.html
- data/
  foo/foo.json
  bar/bar.json
- index/
  foo/index.json
  bar/index.json
```

**Comment by dobromir-hristov** [comment]
When we developed this feature with Ethan, afaik the `index.json` was meant to hold multiple technologies in case we support those in the future, as @d-ronnqvist said.

As far as docc-render is concerned, there should be no extra work to do. If you navigate from `FooKit` to `BarKit` it should just try to find those in the JSON, for the language you are on.

**Comment by TosinAF** [comment]
@adam-rocska also happy to help if possible.

**Comment by d-ronnqvist** [comment]
This is supported by https://github.com/swiftlang/swift-docc/pull/821
