### ISSUE TITLE
`@DeprecationSummary` directive doesn't always have an effect

### ISSUE THREAD

**Issue by anferbui** [swiftlang/swift-docc#932]
### Description

When specifying the `@DeprecationSummary` directive in a symbol extension markdown file, the directive doesn't take effect if the symbol has documentation.

If you define a symbol with multiple lines of source code documentation, and then attempt to deprecate the symbol from a symbol extension markdown file, the result is that the symbol is not deprecated as expected.

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Expected Behavior

I expected the symbol `ExampleDeprecated` to be marked as deprecated in my documentation, like this:
<img width="769" alt="Screenshot 2024-05-29 at 16 14 45" src="https://github.com/apple/swift-docc/assets/15234535/a221d70d-078f-44bf-91d9-d7bb628ef358">

### Actual behavior

But in actuality, the `@DeprecationSummary` directive has no effect when using the default merge behaviour (`append`), and the result is the following:
<img width="808" alt="Screenshot 2024-05-29 at 16 12 33" src="https://github.com/apple/swift-docc/assets/15234535/624c1810-8d0d-45f8-ba51-d66470899a8b">

I can only get the `@DeprecationSummary` directive to have an effect when setting the merge behaviour to be `override`:
```md
@Metadata {
    @DocumentationExtension(mergeBehavior: override)
}
```

### Steps To Reproduce

1. Define a symbol and add multiple lines of documentation in the source code, like so:
```swift
/// I am adding some amazing documentation for my new struct.
///
/// ## Overview
///
/// In fact it's so cool, that it even needs some markdown.
public struct ExampleDeprecated {}
```
2. Deprecate the symbol from a symbol extension markdown file:
```md
# ``ExampleDeprecated``

@DeprecationSummary {
 This is my deprecation text.
}

This struct is deprecated because I needed an example.
```

### Swift-DocC Version Information

037f0bcca7b1aa75551bd9b46825287c159a86b5

### Swift Compiler Version Information

```shell
❯ swiftc --version
swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx15.0
```

**Comment by Rajveer100** [comment]
@anferbui 
If I remember correctly, `@DeprecationSummary` requires a condition as such:

```swift
@available(*, deprecated, message: "This was deprecated.")
public struct ExampleDeprecated {}
```

Xcode even throws a warning for this:

```
warning: 'ExampleDeprecated' isn't unconditionally deprecated
```

**Comment by anferbui** [comment]
I believe that `@DeprecationSummary` can be used to override the symbol graph and mark a symbol as deprecated, or at least that seems to be the behavior in `main`.

It does output a warning to make the writer aware but in most cases it will continue and mark the symbol as deprecated, except for this specific case where the symbol has multi-line comment documentation, which causes the directive to not be parsed (most, if not all, directives are only parsed in the abstract).
https://github.com/swiftlang/swift-docc/blob/563b958f424395ddcbd1b657bbceb0cf918cc8e0/Sources/SwiftDocC/Model/DocumentationMarkup.swift#L147-L172
